/** SportShield AI — Takedown Management Page */
import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FileWarning, Download, Send, Clock, CheckCircle2, AlertCircle, ExternalLink, Plus, X, FileText, Shield } from 'lucide-react';
import { GlassCard } from '../components/shared/GlassCard';
import { PageTransition } from '../components/shared/PageTransition';
import { GlowingButton } from '../components/shared/GlowingButton';
import jsPDF from 'jspdf';

type TakedownStatus = 'draft' | 'sent' | 'acknowledged' | 'resolved' | 'rejected';

interface Takedown {
  id: string;
  violationUrl: string;
  platform: string;
  assetName: string;
  status: TakedownStatus;
  createdAt: string;
  sentAt?: string;
  resolvedAt?: string;
  confidence: number;
}

const STATUS_CONFIG: Record<TakedownStatus, { label: string; color: string; icon: React.ElementType }> = {
  draft: { label: 'Draft', color: 'text-zinc-400 bg-zinc-500/10 border-zinc-500/20', icon: FileText },
  sent: { label: 'Sent', color: 'text-blue-400 bg-blue-500/10 border-blue-500/20', icon: Send },
  acknowledged: { label: 'Acknowledged', color: 'text-amber-400 bg-amber-500/10 border-amber-500/20', icon: Clock },
  resolved: { label: 'Resolved', color: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/20', icon: CheckCircle2 },
  rejected: { label: 'Rejected', color: 'text-red-400 bg-red-500/10 border-red-500/20', icon: AlertCircle },
};

// Demo data
const DEMO_TAKEDOWNS: Takedown[] = [
  { id: 'TD-001', violationUrl: 'https://youtube.com/watch?v=pirated123', platform: 'youtube', assetName: 'Champions League Final Highlights', status: 'sent', createdAt: '2026-04-08T10:00:00Z', sentAt: '2026-04-08T10:05:00Z', confidence: 94 },
  { id: 'TD-002', violationUrl: 'https://twitter.com/user/status/123456', platform: 'twitter', assetName: 'Premier League Goal Compilation', status: 'resolved', createdAt: '2026-04-07T14:30:00Z', sentAt: '2026-04-07T14:35:00Z', resolvedAt: '2026-04-08T09:00:00Z', confidence: 87 },
  { id: 'TD-003', violationUrl: 'https://instagram.com/p/abc123/', platform: 'instagram', assetName: 'Team Logo - Official Badge', status: 'acknowledged', createdAt: '2026-04-06T08:00:00Z', sentAt: '2026-04-06T08:10:00Z', confidence: 91 },
  { id: 'TD-004', violationUrl: 'https://tiktok.com/@user/video/789', platform: 'tiktok', assetName: 'Match Day Promo Video', status: 'draft', createdAt: '2026-04-09T16:00:00Z', confidence: 78 },
  { id: 'TD-005', violationUrl: 'https://example.com/stolen-content', platform: 'web', assetName: 'Exclusive Interview Clip', status: 'rejected', createdAt: '2026-04-05T12:00:00Z', sentAt: '2026-04-05T12:15:00Z', confidence: 65 },
];

export default function Takedowns() {
  const [takedowns, setTakedowns] = useState<Takedown[]>(DEMO_TAKEDOWNS);
  const [showGenerator, setShowGenerator] = useState(false);
  const [filter, setFilter] = useState<TakedownStatus | 'all'>('all');
  const [searchQuery, setSearchQuery] = useState('');
  
  // New Takedown Form State
  const [newUrl, setNewUrl] = useState('');
  const [newPlatform, setNewPlatform] = useState('youtube');
  const [newAsset, setNewAsset] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  const filtered = takedowns.filter(t => {
    const matchesFilter = filter === 'all' || t.status === filter;
    const matchesSearch = t.assetName.toLowerCase().includes(searchQuery.toLowerCase()) || 
                          t.violationUrl.toLowerCase().includes(searchQuery.toLowerCase()) ||
                          t.id.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesFilter && matchesSearch;
  });
  const counts = {
    all: takedowns.length,
    draft: takedowns.filter(t => t.status === 'draft').length,
    sent: takedowns.filter(t => t.status === 'sent').length,
    acknowledged: takedowns.filter(t => t.status === 'acknowledged').length,
    resolved: takedowns.filter(t => t.status === 'resolved').length,
  };

  const generatePDF = (t: Takedown) => {
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.setTextColor(6, 182, 212);
    doc.text('DMCA Takedown Notice', 20, 25);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text('Generated by SportShield AI - IP Protection Platform', 20, 33);
    doc.line(20, 37, 190, 37);

    doc.setFontSize(12);
    doc.setTextColor(30, 30, 30);
    doc.text('To Whom It May Concern,', 20, 50);
    doc.setFontSize(10);

    const body = [
      `I am writing to notify you that the content hosted at the following URL infringes upon`,
      `intellectual property rights owned by the rights holder represented by SportShield AI.`,
      ``,
      `INFRINGING URL:`,
      `${t.violationUrl}`,
      ``,
      `ORIGINAL ASSET:`,
      `${t.assetName}`,
      ``,
      `PLATFORM: ${t.platform.toUpperCase()}`,
      `DETECTION CONFIDENCE: ${t.confidence}%`,
      `DETECTION DATE: ${new Date(t.createdAt).toLocaleDateString()}`,
      `REFERENCE ID: ${t.id}`,
      ``,
      `This letter is a formal notification under the Digital Millennium Copyright Act (DMCA),`,
      `17 U.S.C. § 512. I hereby request that you immediately remove or disable access to the`,
      `infringing material identified above.`,
      ``,
      `I have a good faith belief that the use of the described material is not authorized by the`,
      `copyright owner, its agent, or the law. The information in this notification is accurate,`,
      `and under penalty of perjury, I am authorized to act on behalf of the owner of the`,
      `exclusive right that is allegedly infringed.`,
      ``,
      `This notice was automatically generated and verified by SportShield AI's detection system.`,
      `AI-verified fingerprint match with ${t.confidence}% confidence score.`,
    ];

    let y = 60;
    body.forEach(line => {
      doc.text(line, 20, y);
      y += 6;
    });

    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text(`SportShield AI | Ref: ${t.id} | Generated: ${new Date().toISOString()}`, 20, 280);

    doc.save(`takedown-${t.id}.pdf`);
  };

  const handleCreateTakedown = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newUrl || !newAsset) return;

    setIsSubmitting(true);
    
    // Simulate API call
    setTimeout(() => {
      const newTakedown: Takedown = {
        id: `TD-${String(takedowns.length + 1).padStart(3, '0')}`,
        violationUrl: newUrl,
        platform: newPlatform,
        assetName: newAsset,
        status: 'draft',
        createdAt: new Date().toISOString(),
        confidence: Math.floor(Math.random() * (99 - 70 + 1) + 70) // Random confidence between 70 and 99
      };

      setTakedowns([newTakedown, ...takedowns]);
      setIsSubmitting(false);
      setShowGenerator(false);
      
      // Reset form
      setNewUrl('');
      setNewPlatform('youtube');
      setNewAsset('');
    }, 800);
  };

  return (
    <PageTransition className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-white mb-1">Takedown Requests</h1>
          <p className="text-zinc-400">Generate, track, and manage DMCA takedown notices.</p>
        </div>
        <GlowingButton variant="primary" size="sm" className="gap-2" onClick={() => setShowGenerator(!showGenerator)}>
          <Plus className="w-4 h-4" /> New Takedown
        </GlowingButton>
      </div>

      {/* Stats Row */}
      <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
        {(['all', 'draft', 'sent', 'acknowledged', 'resolved'] as const).map(status => (
          <button
            key={status}
            onClick={() => setFilter(status)}
            className={`px-4 py-3 rounded-xl border text-left transition-all ${
              filter === status
                ? 'bg-[#111827] border-cyan-500/30 shadow-[0_0_15px_rgba(6,182,212,0.1)]'
                : 'bg-[#111827] border-[#1F2937] hover:border-[#374151]'
            }`}
          >
            <p className="text-xs text-zinc-400 capitalize mb-1">{status === 'all' ? 'Total' : status}</p>
            <p className="text-2xl font-bold text-white">{counts[status as keyof typeof counts] ?? 0}</p>
          </button>
        ))}
      </div>

      {/* Takedown List */}
      <GlassCard noPadding>
        <div className="px-6 py-4 border-b border-[#1F2937] bg-[#111827] rounded-t-2xl flex flex-col sm:flex-row gap-4 justify-between items-center">
          <h3 className="text-sm font-semibold text-white">Takedown History</h3>
          <div className="relative w-full sm:w-64">
            <input
              type="text"
              placeholder="Search by ID, asset, or URL..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full bg-[#0B0F19] border border-[#1F2937] rounded-lg pl-3 pr-3 py-1.5 text-sm text-white placeholder-zinc-500 focus:outline-none focus:border-cyan-500/50 transition-colors"
            />
          </div>
        </div>
        <div className="divide-y divide-[#1F2937]">
          <AnimatePresence mode="popLayout">
            {filtered.map((t, i) => {
              const statusCfg = STATUS_CONFIG[t.status];
              return (
                <motion.div
                  key={t.id}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, x: -20 }}
                  transition={{ delay: i * 0.05 }}
                  className="px-6 py-4 flex items-center gap-4 hover:bg-[#1F2937]/50 transition-colors group"
                >
                  <div className={`p-2 rounded-lg border ${statusCfg.color}`}>
                    <statusCfg.icon className="w-4 h-4" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <span className="text-xs font-mono text-cyan-400">{t.id}</span>
                      <span className={`text-[10px] font-bold uppercase px-2 py-0.5 rounded-full border ${statusCfg.color}`}>{statusCfg.label}</span>
                    </div>
                    <p className="text-sm text-zinc-200 truncate">{t.assetName}</p>
                    <p className="text-xs text-zinc-500 truncate flex items-center gap-1 mt-0.5">
                      <ExternalLink className="w-3 h-3" /> {t.violationUrl}
                    </p>
                  </div>
                  <div className="hidden sm:block text-right">
                    <p className="text-xs text-zinc-400">{new Date(t.createdAt).toLocaleDateString()}</p>
                    <p className="text-xs text-zinc-500 capitalize">{t.platform}</p>
                  </div>
                  <div className="flex items-center gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button
                      onClick={() => generatePDF(t)}
                      className="p-2 rounded-lg bg-[#0B0F19] border border-[#1F2937] text-zinc-300 hover:text-white hover:border-cyan-500/30 transition-all"
                      title="Download PDF"
                    >
                      <Download className="w-4 h-4" />
                    </button>
                  </div>
                </motion.div>
              );
            })}
          </AnimatePresence>
          {filtered.length === 0 && (
            <div className="px-6 py-12 text-center">
              <FileWarning className="w-10 h-10 text-zinc-600 mx-auto mb-3" />
              <p className="text-sm text-zinc-500">No takedown requests matching this filter.</p>
            </div>
          )}
        </div>
      </GlassCard>

      {/* New Takedown Modal */}
      <AnimatePresence>
        {showGenerator && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 bg-black/60 backdrop-blur-sm"
              onClick={() => !isSubmitting && setShowGenerator(false)}
            />
            
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="relative w-full max-w-lg bg-[#111827] border border-[#1F2937] rounded-2xl shadow-2xl overflow-hidden z-10 flex flex-col"
            >
              <div className="px-6 py-4 border-b border-[#1F2937] flex items-center justify-between bg-[#111827]/50">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-cyan-500/10 rounded-lg text-cyan-400">
                    <Shield className="w-5 h-5" />
                  </div>
                  <div>
                    <h2 className="text-lg font-semibold text-white">Generate Notice</h2>
                    <p className="text-xs text-zinc-400">Create a new DMCA takedown request</p>
                  </div>
                </div>
                <button 
                  onClick={() => !isSubmitting && setShowGenerator(false)}
                  className="p-2 text-zinc-400 hover:text-white hover:bg-[#1F2937] rounded-lg transition-colors"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              <form onSubmit={handleCreateTakedown} className="p-6 space-y-4">
                <div>
                  <label className="block text-xs font-medium text-zinc-400 mb-1.5">Target URL (Infringing Content)</label>
                  <input
                    type="url"
                    required
                    value={newUrl}
                    onChange={(e) => setNewUrl(e.target.value)}
                    placeholder="https://example.com/pirated-content"
                    className="w-full bg-[#0B0F19] border border-[#1F2937] rounded-xl px-4 py-2.5 text-sm text-white placeholder-zinc-600 focus:outline-none focus:border-cyan-500/50 transition-colors"
                  />
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-xs font-medium text-zinc-400 mb-1.5">Platform</label>
                    <select
                      value={newPlatform}
                      onChange={(e) => setNewPlatform(e.target.value)}
                      className="w-full bg-[#0B0F19] border border-[#1F2937] rounded-xl px-4 py-2.5 text-sm text-white focus:outline-none focus:border-cyan-500/50 transition-colors appearance-none"
                    >
                      <option value="youtube">YouTube</option>
                      <option value="twitter">Twitter / X</option>
                      <option value="instagram">Instagram</option>
                      <option value="tiktok">TikTok</option>
                      <option value="facebook">Facebook</option>
                      <option value="web">Other Website</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-zinc-400 mb-1.5">Original Asset Name</label>
                    <input
                      type="text"
                      required
                      value={newAsset}
                      onChange={(e) => setNewAsset(e.target.value)}
                      placeholder="e.g. Q4 Highlight Reel"
                      className="w-full bg-[#0B0F19] border border-[#1F2937] rounded-xl px-4 py-2.5 text-sm text-white placeholder-zinc-600 focus:outline-none focus:border-cyan-500/50 transition-colors"
                    />
                  </div>
                </div>

                <div className="pt-4 flex justify-end gap-3 border-t border-[#1F2937] mt-6">
                  <button
                    type="button"
                    onClick={() => setShowGenerator(false)}
                    disabled={isSubmitting}
                    className="px-4 py-2 rounded-xl text-sm font-medium text-zinc-300 hover:text-white hover:bg-[#1F2937] transition-colors disabled:opacity-50"
                  >
                    Cancel
                  </button>
                  <GlowingButton
                    variant="primary"
                    size="sm"
                    className="w-32 justify-center"
                    disabled={isSubmitting}
                  >
                    {isSubmitting ? (
                      <span className="flex items-center gap-2">
                        <motion.div
                          animate={{ rotate: 360 }}
                          transition={{ duration: 1, repeat: Infinity, ease: 'linear' }}
                          className="w-4 h-4 border-2 border-white/20 border-t-white rounded-full"
                        />
                        Creating...
                      </span>
                    ) : (
                      'Create Draft'
                    )}
                  </GlowingButton>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </PageTransition>
  );
}
