/** SportShield AI — Client-side PDF evidence generation using jsPDF */
import { jsPDF } from 'jspdf';
import type { Violation, MediaAsset } from '../types';

export function generateEvidencePDF(violation: Violation, asset?: MediaAsset): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Colors
  const primaryColor: [number, number, number] = [26, 60, 110];
  const accentColor: [number, number, number] = [232, 80, 26];
  const grayColor: [number, number, number] = [100, 116, 139];

  // Header bar
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, pageWidth, 35, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('SportShield AI', 15, 18);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text('IP Violation Evidence Report', 15, 28);

  // Date
  doc.setTextColor(...grayColor);
  doc.setFontSize(9);
  doc.text(`Generated: ${new Date().toISOString().split('T')[0]}`, pageWidth - 60, 28);

  let y = 50;

  // Section helper
  const drawSection = (title: string, yPos: number): number => {
    doc.setFillColor(...primaryColor);
    doc.rect(15, yPos - 5, pageWidth - 30, 8, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(title, 18, yPos + 1);
    return yPos + 12;
  };

  const drawRow = (label: string, value: string, yPos: number): number => {
    doc.setTextColor(...grayColor);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(label, 20, yPos);
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(10);
    doc.text(value.substring(0, 80), 70, yPos);
    return yPos + 7;
  };

  // Section 1: Original Asset
  y = drawSection('Section 1: Original Asset', y);
  y = drawRow('Asset Name', asset?.name || 'Unknown', y);
  y = drawRow('File Type', asset?.file_type || 'N/A', y);
  y = drawRow('File Size', asset ? `${(asset.file_size_bytes / 1024 / 1024).toFixed(2)} MB` : 'N/A', y);
  y = drawRow('Upload Date', asset?.created_at ? new Date(asset.created_at).toLocaleDateString() : 'N/A', y);
  y += 8;

  // Section 2: Detected Violation
  y = drawSection('Section 2: Detected Violation', y);
  y = drawRow('Detected URL', violation.detected_url, y);
  y = drawRow('Platform', violation.platform.charAt(0).toUpperCase() + violation.platform.slice(1), y);
  y = drawRow('Severity', violation.severity.toUpperCase(), y);
  y = drawRow('Status', violation.status.charAt(0).toUpperCase() + violation.status.slice(1), y);
  y = drawRow('Detected At', new Date(violation.detected_at).toLocaleString(), y);
  y += 8;

  // Section 3: Analysis
  y = drawSection('Section 3: Analysis', y);
  y = drawRow('pHash Distance', violation.phash_distance?.toString() || 'N/A', y);
  y = drawRow('CNN Similarity', violation.cnn_similarity?.toFixed(4) || 'N/A', y);
  y = drawRow('Confidence', `${violation.confidence_score.toFixed(1)}%`, y);
  y = drawRow('Severity Tier', violation.severity.toUpperCase(), y);
  y += 8;

  // Section 4: Metadata
  y = drawSection('Section 4: Metadata', y);
  y = drawRow('Violation ID', violation.id, y);
  y = drawRow('Asset ID', violation.asset_id, y);
  y += 15;

  // Footer
  doc.setDrawColor(200, 200, 200);
  doc.line(15, y, pageWidth - 15, y);
  y += 8;
  doc.setTextColor(...grayColor);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.text(
    'Generated by SportShield AI | This document can be used as evidence for DMCA filings',
    pageWidth / 2,
    y,
    { align: 'center' }
  );

  // Save
  doc.save(`evidence_${violation.id.substring(0, 8)}.pdf`);
}
